
/*
CREATE PROCEDURE [DBO].[WEBSERVICE_CNPJ] (@CNPJ AS VARCHAR (15))
AS
BEGIN

DECLARE @OBJ INT;
DECLARE @URL VARCHAR(200);
DECLARE @RESPONSE VARCHAR(8000);

SET @URL = 'HTTPS://WWW.RECEITAWS.COM.BR/V1/CNPJ/' + @CNPJ
EXEC SP_OACREATE 'MSXML2.SERVERXMLHTTP', @OBJ OUT
EXEC SP_OAMETHOD @OBJ, 'OPEN', NULL, 'GET', @URL, FALSE
EXEC SP_OAMETHOD @OBJ, 'SEND'
EXEC SP_OAGETPROPERTY @OBJ, 'RESPONSETEXT', @RESPONSE OUT
EXEC SP_OADESTROY @OBJ

		SELECT 
				JSON_VALUE(@RESPONSE, '$.NOME') AS NOME,
				JSON_VALUE(@RESPONSE, '$.DATA_SITUACAO') AS DATA_SITUACAO,
				JSON_VALUE(@RESPONSE, '$.UF') AS UF,
				JSON_VALUE(@RESPONSE, '$.TELEFONE') AS TELEFONE,
				JSON_VALUE(@RESPONSE, '$.EMAIL') AS EMAIL,
				JSON_VALUE(@RESPONSE, '$.SITUACAO') AS SITUACAO,
				JSON_VALUE(@RESPONSE, '$.BAIRRO') AS BAIRRO,
				JSON_VALUE(@RESPONSE, '$.LOGRADOURO') AS LOGRADOURO,
				JSON_VALUE(@RESPONSE, '$.NUMERO') AS NUMERO,
				JSON_VALUE(@RESPONSE, '$.CEP') AS CEP,
				JSON_VALUE(@RESPONSE, '$.MUNICIPIO') AS MUNICIPIO,
				JSON_VALUE(@RESPONSE, '$.ABERTURA') AS ABERTURA,
				JSON_VALUE(@RESPONSE, '$.NATUREZA_JURIDICA') AS NATUREZA_JURIDICA,
				JSON_VALUE(@RESPONSE, '$.CNPJ') AS CNPJ,
				JSON_VALUE(@RESPONSE, '$.ULTIMA_ATUALIZACAO') AS ULTIMA_ATUALIZACAO,
				JSON_VALUE(@RESPONSE, '$.STATUS') AS STATUS,
				JSON_VALUE(@RESPONSE, '$.TIPO') AS TIPO,
				JSON_VALUE(@RESPONSE, '$.FANTASIA') AS FANTASIA,
				JSON_VALUE(@RESPONSE, '$.STATUS') AS STATUS,
				JSON_VALUE(@RESPONSE, '$.MOTIVO_SITUACAO') AS MOTIVO_SITUACAO,
				JSON_VALUE(@RESPONSE, '$.SITUACAO_ESPECIAL') AS SITUACAO_ESPECIAL,
				JSON_VALUE(@RESPONSE, '$.DATA_SITUACAO_ESPECIAL') AS DATA_SITUACAO_ESPECIAL,
				JSON_VALUE(@RESPONSE, '$.CAPITAL_SOCIAL') AS CAPITAL_SOCIAL


END     

GO
*/