DBCC TRACEON (3604);
GO
DBCC PAGE (NEO,1,180,3)
GO

ALTER DATABASE NEO SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DBCC CHECKDB('neo', REPAIR_ALLOW_DATA_LOSS)
DBCC DBREINDEX ('HumanResources.Employee', '', 70);
DBCC SQLPERF(LOGSPACE)
DBCC SHRINKFILE (DataFil1, 7);
DBCC UPDATEUSAGE (0);
GO

GO