USE MASTER
GO

CREATE MASTER KEY
ENCRYPTION BY PASSWORD = 'ABC123';
GO

CREATE CERTIFICATE CertSeguranca
WITH SUBJECT = 'Certificado - Criptografia e Segurança'
GO

BACKUP CERTIFICATE CertSeguranca
 TO FILE = 'C:\CertSeguranca.cer'
 WITH PRIVATE KEY (FILE = C:\CertSeguranca.pvk',
 ENCRYPTION BY PASSWORD = 'ABC123');

USE MEUBANCO
GO

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_128
ENCRYPTION BY SERVER CERTIFICATE CertSeguranca
Go

ALTER DATABASE MEUBANCO
 SET ENCRYPTION ON
GO

Select * from Sys.dm_database_encryption_keys