20--DEMO OPÇÕES ADICIONAIS DE BACKUP E RESTORE

--OPÇÕES DE BACKUP

--CRIA BANCO PARA DEMO OPCOES ADICIONAIS
IF EXISTS (SELECT NULL FROM SYS.DATABASES WHERE NAME = 'SQLSERVER_RS_OPTIONS')
           DROP DATABASE SQLSERVER_RS_OPTIONS
CREATE DATABASE SQLSERVER_RS_OPTIONS
ON PRIMARY
(NAME='SQLSERVER_RS_OPTIONS', FILENAME='C:\temp\SQLServerRS\Dados\SQLSERVER_RS_OPTIONS.mdf')
LOG ON
(NAME = 'SQLSERVER_RS_OPTIONS_LOG', FILENAME = 'C:\temp\SQLServerRS\Log\SQLSERVER_RS_OPTIONS_Log.ldf')
GO

--COPY_ONLY, COMPRESSION, STATS
BACKUP DATABASE SQLSERVER_RS
    TO DISK = 'C:\temp\SQLServerRS\Backup\OPTIONS\SQLSERVER_RS_OPTIONS_Sem_Compression.bak'
  WITH COPY_ONLY
       ,STATS = 1

--COPY_ONLY, COMPRESSION, STATS
BACKUP DATABASE SQLSERVER_RS
    TO DISK = 'C:\temp\SQLServerRS\Backup\OPTIONS\SQLSERVER_RS_OPTIONS_Com_Compression.bak'
  WITH COPY_ONLY
	   ,COMPRESSION
       ,STATS = 1


--RECOVERY / NORECOVERY / REPLACE
USE MASTER
GO
RESTORE FILELISTONLY FROM DISK = 'C:\temp\SQLServerRS\Backup\OPTIONS\SQLSERVER_RS_OPTIONS_Com_Compression.bak'

--SQLSERVER_RS		C:\temp\SQLServerRS\Dados\SQLSERVER_RS.mdf
--SQLSERVER_RS_LOG	C:\temp\SQLServerRS\Log\SQLSERVER_RS_Log.ldf

RESTORE DATABASE SQLSERVER_RS_OPTIONS
   FROM DISK = 'C:\temp\SQLServerRS\Backup\OPTIONS\SQLSERVER_RS_OPTIONS_Com_Compression.bak'
   WITH MOVE 'SQLSERVER_RS' TO 'C:\temp\SQLServerRS\Dados\SQLSERVER_RS_OPTIONS.mdf'
        ,MOVE 'SQLSERVER_RS_LOG' TO 'C:\temp\SQLServerRS\Log\SQLSERVER_RS_OPTIONS_Log.ldf'
		,NORECOVERY
        ,REPLACE   -- SEJA EXTREMAMENTE CAUTELOSO(A) COM O REPLACE

RESTORE DATABASE SQLSERVER_RS_OPTIONS WITH RECOVERY

--MIRROR (LIMTE DE 4 MIRRORS CONTANDO O PRINCIPAL)
--DUPLICAR O BACKUP COM A FINALIDADE DE CRIAR REDUNDÂNCIA OU DISTRIBUIÇÃO DO MESMO.
BACKUP DATABASE SQLSERVER_RS_OPTIONS
    TO DISK = 'C:\temp\SQLServerRS\Backup\MIRROR1\SQLSERVER_RS_OPTIONS_MIRROR10.bak'
MIRROR TO DISK = 'C:\temp\SQLServerRS\Backup\MIRROR1\SQLSERVER_RS_OPTIONS_MIRRO11.bak'
MIRROR TO DISK = 'C:\temp\SQLServerRS\Backup\MIRROR2\SQLSERVER_RS_OPTIONS_MIRRO20.bak'
MIRROR TO DISK = 'C:\temp\SQLServerRS\Backup\MIRROR2\SQLSERVER_RS_OPTIONS_MIRRO22.bak'
  WITH FORMAT
       ,STATS = 1


--SPLIT
--GANHO DE PERFORMANCE E PROBLEMAS DE ESPAÇO, POIS DIVIDE EM TAMANHOS IGUAIS O BACKUP...
BACKUP DATABASE SQLSERVER_RS_OPTIONS
    TO DISK = 'C:\temp\SQLServerRS\Backup\SPLIT1\SQLSERVER_RS_OPTIONS_1.bak'
	   ,DISK = 'C:\temp\SQLServerRS\Backup\SPLIT2\SQLSERVER_RS_OPTIONS_2.bak'
	   ,DISK = 'C:\temp\SQLServerRS\Backup\SPLIT3\SQLSERVER_RS_OPTIONS_3.bak'
  WITH COMPRESSION
       ,STATS = 35
	 
