--RESTORE STOPAT | STANDBY
--REALTIME
RESTORE FILELISTONLY FROM DISK = 'C:\temp\SQLServerRS\Backup\'

/*


*/

--RESTORE BACKUP FULL
RESTORE DATABASE SQLSERVERRS_STOPAT
   FROM DISK = 'C:\temp\SQLServerRS\Backup\'
   WITH NORECOVERY
		,MOVE '' TO 'C:\temp\SQLServerRS\Dados\'
		,MOVE '' TO 'C:\temp\SQLServerRS\Log\'
	    ,STATS = 3

-- RESTORE BACKUP DIFERENCIAL
RESTORE DATABASE SQLSERVERRS_STOPAT
   FROM DISK = 'C:\temp\SQLServerRS\Backup\'
   WITH NORECOVERY
		,STATS =1

--RESTORE BACKUPS DE LOG
RESTORE LOG SQLSERVERRS_STOPAT
   FROM DISK = 'C:\temp\SQLServerRS\Backup\'
   WITH NORECOVERY
		,STOPAT = '2012-12-05 14:27:42.213'
		,STANDBY = ''


USE SQLSERVERRS_STOPAT
GO
SELECT * 
  FROM TB_SQLSERVERRS
 ORDER BY ID DESC


 --RESTORE BACKUPS DE LOG
RESTORE LOG SQLSERVERRS_STOPAT
   FROM DISK = 'C:\temp\SQLServerRS\Backup\'
   WITH NORECOVERY
		,STOPAT = '2012-12-05 14:27:42.213'
		,STANDBY = 'C:\temp\SQLServerRS\SQLSERVERRS_STOPAT.sb'





--EXEMPLO DE SINTAXE DE RESTORE DE PÁGINA

--LISTA DAS PÁGINAS SUSPEITAS POR BANCO.   
SELECT * FROM MSDB..suspect_pages



RESTORE DATABASE <database> PAGE='1:57, 1:202, 1:916, 1:1016'
   FROM <file_backup_of_file_B> 
   WITH NORECOVERY;

RESTORE LOG <database> FROM <log_backup> 
   WITH NORECOVERY;

BACKUP LOG <database> TO <new_log_backup>; 

RESTORE LOG <database> FROM <new_log_backup> WITH RECOVERY;
GO