--Instancia do Servidor Principal (AAS\SQL2008)
CREATE ENDPOINT [Mirroring]
	AUTHORIZATION [AAS\Alex]
	STATE=STARTED
	AS TCP (LISTENER_PORT = 5022, LISTENER_IP = ALL)
	FOR DATA_MIRRORING (ROLE = PARTNER, AUTHENTICATION = WINDOWS NEGOTIATE
	,	ENCRYPTION = REQUIRED ALGORITHM RC4)

--Instancia do Servidor Espelho (AAS\SQL2008_ESPELHO)
CREATE ENDPOINT [Mirroring]
	AUTHORIZATION [AAS\Alex]
	STATE=STARTED
	AS TCP (LISTENER_PORT = 5023, LISTENER_IP = ALL)
	FOR DATA_MIRRORING (ROLE = PARTNER, AUTHENTICATION = WINDOWS NEGOTIATE
	,	ENCRYPTION = REQUIRED ALGORITHM RC4)
	
--Instancia do Servidor Testemunha (AAS\SQL2008_WITNESS)
CREATE ENDPOINT [Mirroring]
	AUTHORIZATION [AAS\Alex]
	STATE=STARTED
	AS TCP (LISTENER_PORT = 5024, LISTENER_IP = ALL)
	FOR DATA_MIRRORING (ROLE = WITNESS, AUTHENTICATION = WINDOWS NEGOTIATE
	,	ENCRYPTION = REQUIRED ALGORITHM RC4)
	
DROP ENDPOINT [Mirroring]

-- Ver os EDNPOINTS Criados
SELECT * FROM sys.database_mirroring
SELECT * FROM sys.database_mirroring_endpoints
SELECT * FROM sys.database_mirroring_witnesses

-- Criando o Backup no Principal para ser restaurado no espelho... (AAS\SQL2008)
BACKUP DATABASE EstudoSQL2008 TO DISK = 'D:\Alex\SQL Server\Backups\EstudoSQL2008.bak'
BACKUP LOG EstudoSQL2008 TO DISK = 'D:\Alex\SQL Server\Backups\EstudoSQL2008_log.trn'

-- Restaurando o Backup no espelho (AAS\SQL2008_ESPELHO)
RESTORE DATABASE EstudoSQL2008 FROM DISK = 'D:\Alex\SQL Server\Backups\EstudoSQL2008.bak'
WITH REPLACE, NORECOVERY;
RESTORE DATABASE EstudoSQL2008 FROM DISK = 'D:\Alex\SQL Server\Backups\EstudoSQL2008_log.trn'
WITH KEEP_REPLICATION, NORECOVERY;

-- No Servidor Espelho (AAS\SQL2008_ESPELHO)
ALTER DATABASE EstudoSQL2008
SET PARTNER = 'TCP://AAS:5023';
--ALTER DATABASE EstudoSQL2008 SET PARTNER OFF

-- No Servidor Principal (AAS\SQL2008)
ALTER DATABASE EstudoSQL2008
SET PARTNER = 'TCP://AAS:5022';

ALTER DATABASE EstudoSQL2008
SET WITNESS = 'TCP://AAS:5024';

Select * from sys.database_mirroring_endpoints

RESTORE DATABASE EstudoSQL2008 WITH RECOVERY;