CREATE DATABASE TK432 ON  PRIMARY 
( NAME = N'TK432_Data', FILENAME = N'c:\test\TK432.mdf' , SIZE = 8MB , MAXSIZE = UNLIMITED, FILEGROWTH = 16MB ), 
 FILEGROUP FG1 
( NAME = N'TK432_Data2', FILENAME = N'c:\test\TK432.ndf' , SIZE = 8MB , MAXSIZE = UNLIMITED, FILEGROWTH = 16MB ),
 FILEGROUP Documents CONTAINS FILESTREAM  DEFAULT 
( NAME = N'Documents', FILENAME = N'c:\test\TK432Documents' )
 LOG ON 
( NAME = N'TK432_Log', FILENAME = N'c:\test\TK432.ldf' , SIZE = 8MB , MAXSIZE = 2048GB , FILEGROWTH = 16MB )
GO

ALTER DATABASE DB_TK432
MODIFY FILEGROUP FG1
DEFAULT
GO

ALTER DATABASE AdventureWorks
    SET RECOVERY FULL
GO

-- Colocando o Banco como somente Leitura
ALTER DATABASE DB_TK432
SET READ_ONLY

INSERT INTO Sc_Teste.Table_1
VALUES ('Testando 22')

SELECT * FROM Sc_Teste.Table_1

-- Colocando o Banco como Leitura e Escrita
ALTER DATABASE DB_TK432
SET READ_WRITE